### PR TITLE
Fix verify macro to support mocks created inside fixture classes

### LINKED ISSUE #212: "aMock wasNever called" treats mocks defined inside fixture objects as method calls
We use fixture objects (not traits) and `org.scalatest.fixture._` specs, so mocks are provided into the test like so

```scala
class Fixture {
  val service = mock[Service]
}

// ...

"mySpec" should "test something" in { f: Fixture =>
  f.service wasNever called
}
```

`VerifyMacro` treats `f.service` as a method call, and I get a `NotAMockException`.

I can think of a few ways to solve it:

1. Define a different syntax for verifications on a mock vs a method call. Maybe `aMock wasNever interactedWith`, or even just expose the regular `verifyNoInteractions`?

2. I don't think we can distinguish a method call from a field access using quasiquotes - `q"$a.$b"` matches both if the method has no parens or type args. Here's what I think we could do, however:
    - Method calls with parens is always `Apply` tree
    - Field access or no-paren method calls is always `Select`
    
    We could match against these types specifically, and in the case of `Select`, check if the penultimate identifier is a mock - and if so, treat it as a method call, otherwise as field access.
    To illustrate:
    ```scala
    fixture.aMock wasNever called
    ```
    translates into
    ```scala
    if (mockingDetails(fixture).isMock) verify(fixture, never()).aMock
    else verifyZeroInteractions(fixture.aMock)
    ```

3. (Kinda orthogonal to the above) In Expect DSL, define `on` for mock objects on the right side, and that would be distinct from `to` which only expects method calls, so we'd use
    ```scala
    expect no calls on aMock
    ```
    instead of
    ```scala
    expect no calls to aMock
    ```
    `on` vs `to` would be such a subtle change though so I can imagine errors in these lines be frustrating to diagnose... Maybe a better alternative would be `expect no interactions with aMock`, or again, just expose the vanilla `verifyNoInteractions`/alias it to `expectNoInteractions`

### PR DESCRIPTION
**Pull request by ultrasecreth**
Fixes #212 

@einholen

Fixes the postfix verification, new DSL to be addressed in future PR

### CODE REVIEW

File: macro/src/main/scala/org/mockito/VerifyMacro.scala [hunk 1]
```diff
@@ -97,13 +97,16 @@ private[mockito] trait VerificationMacroTransformer {
...
+        q"""
+           if (_root_.org.mockito.MockitoSugar.mockingDetails($a).isMock) ${transformInvocation(c)(q"$a.$b", order, q"_root_.org.mockito.VerifyMacro.Never")}
+           else ${called match {
+          case q"$_.called"      => q"verification(_root_.org.mockito.MockitoSugar.verifyZeroInteractions($a.$b))"
+          case q"$_.calledAgain" => q"verification(_root_.org.mockito.MockitoSugar.verifyNoMoreInteractions($a.$b))"
           case q"$_.calledAgain.apply($_.ignoringStubs)" =>
-            q"verification(_root_.org.mockito.MockitoSugar.verifyNoMoreInteractions(_root_.org.mockito.MockitoSugar.ignoreStubs($obj): _*))"
-        }
+            q"verification(_root_.org.mockito.MockitoSugar.verifyNoMoreInteractions(_root_.org.mockito.MockitoSugar.ignoreStubs($a.$b): _*))"
+        }}
```
Comment (einholen) [inline macro/src/main/scala/org/mockito/VerifyMacro.scala]: ah sweet, easier fix than I envisioned!

Wanna maybe extract `${called match { ... }}` part into another variable for readability?

**Review by einholen — APPROVED** [review]

File: macro/src/main/scala/org/mockito/VerifyMacro.scala (hunk 1 above)
Comment (ultrasecreth) [reply macro/src/main/scala/org/mockito/VerifyMacro.scala]: Good point
