### PR TITLE
Close mocking session on aborted Scalatest runs

### LINKED ISSUE #211: Usage of scalatest IdiomaticMockito produces "unfinished mocking session" errors
Hey Bruno!
I'm upgrading mockito-scala in my large project from 1.5.18 to 1.13.0 (and scalatest from 3.0.8 to 3.1.1 which is a big change). Scala 2.13.
All the tests in the project derive from `org.mockito.scalatest.IdiomaticMockito`. After upgrading and fixing all compile errors, when I run all tests, about 700 of them pass, and suddenly, after a certain point, every single test starts failing with this:

```
[info]   org.mockito.exceptions.misusing.UnfinishedMockingSessionException: Unfinished mocking session detected.
[info] Previous MockitoSession was not concluded with 'finishMocking()'.
[info] For examples of correct usage see javadoc for MockitoSession class.
```

And then obviously whichever of the failed tests I rerun manually, they pass.
Feels like something somewhere sets a static state and doesn't unset it - or perhaps there is a race condition. The project has `parallelExecution in Test := false` though...

Any ideas what it could be?
Could it be the fact that `MockitoSessionFixture` doesn't catch exceptions? I haven't been able to figure out the exact trigger for the failures but suspect it can start after a normal test failure.
Just letting you know in case you have ideas, but I'll investigate more.

### PR DESCRIPTION
**Pull request by einholen**
Fixes #211 .

A Scalatest test case run (`super.withFixture(test)`) will actually throw an exception when the entire test suite must be aborted (ie initialization errors or just non-`Exception` errors such as `StackOverflowError`). In such a case, the current open mocking session is never closed, and all subsequent test suites using the same base class start to fail because Mockito does not allow creating a new session when there's an unclosed one.
We can fix it by catching all throwables, trying to close the session and rethrow.

### CODE REVIEW

File: scalatest/src/main/scala/org/mockito/scalatest/MockitoSessionFixture.scala [hunk 1]
```diff
@@ -10,9 +10,18 @@ private[mockito] trait MockitoSessionFixture extends TestSuite { this: Suite =>
...
     val session = MockitoScalaSession(name = s"${test.name} - session", strictness)
-    val result  = super.withFixture(test)
+
     // if the test has thrown an exception, the session will check first if the exception could be related to a mis-use
     // of mockito, if not, it will throw nothing so the real test failure can be reported by the ScalaTest
+    val result =
+      try {
+        super.withFixture(test)
+      } catch {
+        case t: Throwable =>
```
Comment (einholen) [inline scalatest/src/main/scala/org/mockito/scalatest/MockitoSessionFixture.scala]: I'm not 100% sure we should try catching _all_ throwables though. Perhaps only `NonFatal` will do

File: scalatest/src/main/scala/org/mockito/scalatest/MockitoSessionFixture.scala [hunk 2]
```diff
@@ -25,15 +31,13 @@ private[mockito] trait MockitoSessionAsyncFixture extends AsyncTestSuite { this:
...
-    // if the test has thrown an exception, the session will check first if the exception could be related to a mis-use
-    // of mockito, if not, it will throw nothing so the real test failure can be reported by the ScalaTest
     val result =
       try {
         super.withFixture(test)
       } catch {
-        case NonFatal(ex) =>
-          session.finishMocking(Some(ex))
-          throw ex
+        case t: Throwable =>
```
Comment (ultrasecreth) [inline scalatest/src/main/scala/org/mockito/scalatest/MockitoSessionFixture.scala:38]: So the problem was that we were not catching the `StackOverflowException` and hence not closing the session appropriately?

Comment (einholen) [reply scalatest/src/main/scala/org/mockito/scalatest/MockitoSessionFixture.scala:38]: yep, and `NonFatal(e)` wouldn't catch it either - `StackOverflowError` is a `VirtualMachineError` which is technically fatal for some reason even if it's not

Comment (einholen) [reply scalatest/src/main/scala/org/mockito/scalatest/MockitoSessionFixture.scala:38]: And in synchronous spec, no exceptions are caught - but some do get thrown when a suite is aborted
